require("core.keymap")
require("core.option")
require("core.manager")
require("config.treesitter")
require("config.fzf")
require("config.lualine")
require("config.colorscheme")
require("config.autopairs")
require("config.indent")
require("config.neogit")
require("config.mason")
require("config.lspconfig")
require("config.comment")
require("config.todo")
require("config.conform")
require("config.gitsign")
require("config.trouble")
-- require("config.neotest")
require("config.lazydev")
require("config.fidget")
-- require("config.snack")
-- require("config.mini")
