require("core.keymap")
require("core.option")
require("core.manager")
require("config.treesitter")
require("config.fzf")
require("config.lualine")
require("config.autopairs")
require("config.indent")
require("config.mason")
require("config.lazydev")
require("config.lspconfig")
require("config.comment")
require("config.todo")
require("config.conform")
require("config.gitsign")
require("config.trouble")
require("config.lint")
require("config.fidget")
require("config.doge")
-- require("config.neotest")
-- require("config.neogit")
require("config.colorscheme")
