require("core.keymap")
require("core.option")
require("manager.lazy")
-- require("configs.whichkey")
require("configs.lualine")
require("configs.treesitter")
require("configs.gitsigns")
require("configs.autopairs")
require("configs.fzf")
require("configs.mini")
require("configs.lspzero")
require("configs.lspconfig")
require("configs.conform")
-- require("configs.nonels")
-- require("configs.mayukai")
require("configs.comment")
-- require("configs.terminal")
